name: Bug report
title: "[Bug][Module Name] Bug title"
description: Problems and issues with code of Metal
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure what you are reporting is indeed a bug with reproducible steps.
        For better global communication, Please write in English.

        If you feel the description in English is not clear, then you can append description in Chinese, thanks!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/CheneyYin/metal/issues?q=is%3Aissue+label%3A%22bug%22)
        first to see whether the same issue was reported already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/CheneyYin/metal/issues?q=is%3Aissue+label%3A%22bug%22) and found
            no similar issues.
          required: true

  - type: textarea
    attributes:
      label: What happened
      description: Describe what happened.
      placeholder: >
        Please provide the context in which the problem occurred and explain what happened
    validations:
      required: true

  - type: textarea
    attributes:
      label: Metal Version
      description: Provide Metal version.
      placeholder: >
        Please provide the version of Metal.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Spark Version
      description: Provide Spark version.
      placeholder: >
        Please provide the version of Spark.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Metal Spec
      description: Provide Metal Spec, please delete sensitive information to prevent information leakage
      placeholder: >
        Please provide the Metal Spec here.
      render: json
    validations:
      required: true

  - type: textarea
    attributes:
      label: Running Command
      description: Provide the Running Command you begin and run Metal.
      placeholder: >
        Please provide the running command here.
      render: shell
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error Exception
      description: Provide the error exception when you run your command.
      placeholder: >
        Please provide the error exception here.
      render: log
    validations:
      required: true

  - type: textarea
    attributes:
      label: Java or Scala Version
      description: Provide Java or Scala Version.
      placeholder: >
        Please provide the version of Java or Scala.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots
      description: Provide the screenshots if necessary.
      placeholder: >
        Please copy-paste the screenshots here.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the fix.
        seatunnel is a totally community-driven project and we love to bring new contributors in.
      options:
        - label: Yes I am willing to submit a PR!

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: |
        The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: >
            I agree to follow this project's
            [Code of Conduct](https://github.com/CheneyYin/metal/blob/master/CODE_OF_CONDUCT.md)
          required: true

  - type: markdown
    attributes:
      value: "Thanks for completing our form, and we will reply you as soon as possible."